sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t asm06-poc/docker-poc -f Dockerfile.dev .

script:
  - docker run -e CI=true asm06-poc/docker-poc npm run test